### ISSUE TITLE
About reference for Deepseek VL

### ISSUE THREAD

**Issue by zhangmozhe** [gokayfem/Awesome-VLM-Architectures#2]
Thanks for your awesome summary. Could you please also mention the DeepSeek VL series to the repo?

Paper: https://arxiv.org/abs/2403.05525
Github: https://github.com/deepseek-ai/DeepSeek-VL
Huggingface demo: https://huggingface.co/spaces/deepseek-ai/DeepSeek-VL-7B.

Thanks!

**Comment by gokayfem** [comment]
I've added Deepseek VL, Mantis, Idefics2, moondream1, moondream2 and InternLM-XComposer2-4KHD. If you have other suggestions i can add them also.

**Comment by zhangmozhe** [comment]
Great work. Thanks!
